--TEST--
Binary type: subtype 0x09 Vector INT8
--DESCRIPTION--
Generated by scripts/convert-bson-corpus-tests.php

DO NOT EDIT THIS FILE
--FILE--
<?php

require_once __DIR__ . '/../utils/basic.inc';

$canonicalBson = hex2bin('11000000057800040000000903007F0700');
$canonicalExtJson = '{"x": {"$binary": {"base64": "AwB/Bw==", "subType": "09"}}}';

// Canonical BSON -> BSON object -> Canonical BSON
echo bin2hex((string) MongoDB\BSON\Document::fromBSON($canonicalBson)), "\n";

// Canonical BSON -> BSON object -> Canonical extJSON
echo json_canonicalize(MongoDB\BSON\Document::fromBSON($canonicalBson)->toCanonicalExtendedJSON()), "\n";

// Canonical extJSON -> BSON object -> Canonical BSON
echo bin2hex((string) MongoDB\BSON\Document::fromJSON($canonicalExtJson)), "\n";

?>
===DONE===
<?php exit(0); ?>
--EXPECT--
11000000057800040000000903007f0700
{"x":{"$binary":{"base64":"AwB\/Bw==","subType":"09"}}}
11000000057800040000000903007f0700
===DONE===