#
# Build variants to build the driver - these are run for all operating systems and PHP versions we support
#
buildvariants:
  # Debian
  - name: build-debian12
    display_name: "Build: Debian 12"
    tags: ["build", "debian", "x64", "pr", "tag"]
    run_on: debian12-small
    tasks:
      - name: "build-php-openssl3"
      - name: "build-php-libmongoc"
  - name: build-debian11
    display_name: "Build: Debian 11"
    tags: ["build", "debian", "x64", "pr", "tag"]
    run_on: debian11-small
    tasks:
      - name: "build-all-php"
  - name: build-debian10
    display_name: "Build: Debian 10"
    tags: ["build", "debian", "x64", "pr", "tag"]
    run_on: debian10-small
    tasks:
      - name: "build-all-php"
  - name: build-debian92
    display_name: "Build: Debian 9.2"
    tags: ["build", "debian", "x64", "pr", "tag"]
    run_on: debian92-small
    tasks:
      - name: "build-all-php"

  # RHEL
  - name: build-rhel90
    display_name: "Build: RHEL 9.0"
    tags: ["build", "rhel", "x64", "pr", "tag"]
    run_on: rhel90-small
    tasks:
      - name: "build-php-openssl3"
  - name: build-rhel8-zseries
    display_name: "Build: RHEL 8 Zseries"
    tags: ["build", "rhel", "zseries", "tag"]
    run_on: rhel8-zseries-small
    tasks:
      - name: "build-all-php"
  - name: build-rhel8-arm64
    display_name: "Build: RHEL 8 ARM64"
    tags: ["build", "rhel", "arm64", "tag"]
    run_on: rhel82-arm64
    tasks:
      - name: "build-all-php"
  - name: build-rhel8-power8
    display_name: "Build: RHEL 8 Power8"
    tags: ["build", "rhel", "power8", "tag"]
    run_on: rhel8-power-large
    tasks:
      - name: "build-all-php"
  - name: build-rhel8
    display_name: "Build: RHEL 8 x64"
    tags: ["build", "rhel", "x64", "pr", "tag"]
    run_on: rhel80-small
    tasks:
      - name: "build-all-php"

  # Ubuntu LTS
  - name: build-ubuntu2204
    display_name: "Build: Ubuntu 22.04 x64"
    tags: ["build", "ubuntu", "x64", "pr", "tag"]
    run_on: ubuntu2204-small
    tasks:
      - name: "build-php-openssl3"
  - name: build-ubuntu2204-arm64
    display_name: "Build: Ubuntu 22.04 ARM64"
    tags: ["build", "ubuntu", "arm64", "tag"]
    run_on: ubuntu2204-arm64-small
    tasks:
      - name: "build-php-openssl3"
  - name: build-ubuntu2004
    display_name: "Build: Ubuntu 20.04 x64"
    tags: ["build", "ubuntu", "x64", "tag"]
    run_on: ubuntu2004-small
    tasks:
      - name: "build-all-php"
  - name: build-ubuntu2004-arm64
    display_name: "Build: Ubuntu 20.04 ARM64"
    tags: ["build", "ubuntu", "arm64", "tag"]
    run_on: ubuntu2004-arm64-small
    tasks:
      - name: "build-all-php"
