#
# Build variants to build the driver - these are run for all operating systems and PHP versions we support
#
buildvariants:
  # Debian
  - name: build-debian11
    display_name: "Build: Debian 11"
    run_on: debian11-small
    tasks:
      - name: ".build"
  - name: build-debian10
    display_name: "Build: Debian 10"
    run_on: debian10-small
    tasks:
      - name: ".build"
  - name: build-debian92
    display_name: "Build: Debian 9.2"
    run_on: debian92-small
    tasks:
      - name: ".build"

  # RHEL
  - name: build-rhel90
    display_name: "Build: RHEL 9.0"
    run_on: rhel90-small
    tasks:
      - name: ".build !.php7.4 !.php8.0"
  - name: build-rhel83-zseries
    display_name: "Build: RHEL 8.3 Zseries"
    run_on: rhel83-zseries-small
    tasks:
      - name: ".build"
  - name: build-rhel82-arm64
    display_name: "Build: RHEL 8.2 ARM64"
    run_on: rhel82-arm64
    tasks:
      - name: ".build"
  - name: build-rhel81-power8
    display_name: "Build: RHEL 8.1 Power8"
    run_on: rhel81-power8-large
    tasks:
      - name: ".build"
  - name: build-rhel80
    display_name: "Build: RHEL 8.0"
    run_on: rhel80-small
    tasks:
      - name: ".build"
  - name: build-rhel76
    display_name: "Build: RHEL 7.6"
    run_on: rhel76-small
    tasks:
      - name: ".build"

  # Ubuntu LTS
  - name: build-ubuntu2204
    display_name: "Build: Ubuntu 22.04 x64"
    run_on: ubuntu2204-small
    tasks:
      - name: ".build !.php7.4 !.php8.0"
  - name: build-ubuntu2204-arm64
    display_name: "Build: Ubuntu 22.04 ARM64"
    run_on: ubuntu2204-arm64-small
    tasks:
      - name: ".build !.php7.4 !.php8.0"
  - name: build-ubuntu2004
    display_name: "Build: Ubuntu 20.04 x64"
    run_on: ubuntu2004-small
    tasks:
      - name: ".build"
  - name: build-ubuntu2004-arm64
    display_name: "Build: Ubuntu 20.04 ARM64"
    run_on: ubuntu2004-arm64-small
    tasks:
      - name: ".build"
