tasks:
  - name: "build-php-8.2"
    tags: ["build", "php8.2"]
    commands:
      - func: "compile driver"
        vars:
          PHP_VERSION: "8.2"
      - func: "upload build"

  - name: "build-php-8.1"
    tags: ["build", "php8.1"]
    commands:
      - func: "compile driver"
        vars:
          PHP_VERSION: "8.1"
      - func: "upload build"

  - name: "build-php-8.0"
    tags: ["build", "php8.0"]
    commands:
      - func: "compile driver"
        vars:
          PHP_VERSION: "8.0"
      - func: "upload build"

  - name: "build-php-7.4"
    tags: ["build", "php7.4"]
    commands:
      - func: "compile driver"
        vars:
          PHP_VERSION: "7.4"
      - func: "upload build"
