buildvariants:
  # Test alternative storage engines on MongoDB 4.0
  - matrix_name: "test-ocsp"
    matrix_spec: { "os": "debian10", "mongodb-versions": "*", "php-edge-versions": "latest-stable" }
    display_name: "OCSP tests - ${mongodb-versions}"
    exclude_spec:
      # OCSP is available from MongoDB 4.4+ (Debian 10 has MongoDB 4.4+)
      - { "os": "debian10", "mongodb-versions": ["3.6", "4.0", "4.2"], "php-edge-versions": "latest-stable" }
    tasks:
      - name: ".ocsp"
