axes:
  - id: os
    display_name: OS
    values:
      # Debian
      - id: debian11
        display_name: "Debian 11"
        run_on: debian11-small
      - id: debian10
        display_name: "Debian 10"
        run_on: debian10-small
      - id: debian92
        display_name: "Debian 9.2"
        run_on: debian92-small

      # RHEL
      - id: rhel90
        display_name: "RHEL 9.0"
        run_on: rhel90-small
      - id: rhel83-zseries
        display_name: "RHEL 8.3 Zseries"
        run_on: rhel83-zseries-small
      - id: rhel82-arm64
        display_name: "RHEL 8.2 ARM64"
        run_on: rhel82-arm64-small
      - id: rhel81-power8
        display_name: "RHEL 8.1 Power8"
        run_on: rhel81-power8-large
      - id: rhel80
        display_name: "RHEL 8.0"
        run_on: rhel80-small
      - id: rhel76
        display_name: "RHEL 7.6"
        run_on: rhel76-small

      # Ubuntu LTS
      - id: ubuntu2204
        display_name: "Ubuntu 22.04 x64"
        run_on: ubuntu2204-small
      - id: ubuntu2204-arm64
        display_name: "Ubuntu 22.04 ARM64"
        run_on: ubuntu2204-arm64-small
      - id: ubuntu2004
        display_name: "Ubuntu 20.04 x64"
        run_on: ubuntu2004-small
      - id: ubuntu2004-arm64
        display_name: "Ubuntu 20.04 ARM64"
        run_on: ubuntu2004-arm64-small

  - id: storage-engine
    display_name: Storage
    values:
      - id: mmapv1
        display_name: MMAPv1
        variables:
          STORAGE_ENGINE: "mmapv1"
      - id: wiredtiger
        display_name: WiredTiger
        variables:
          STORAGE_ENGINE: "wiredtiger"
      - id: inmemory
        display_name: InMemory
        variables:
          STORAGE_ENGINE: "inmemory"

  - id: libmongoc-version
    display_name: libmongoc version
    values:
      - id: "lowest-supported"
        display_name: "1.25-dev"
        variables:
          LIBMONGOC_VERSION: "master"
#      - id: "upcoming-stable"
#        display_name: "1.25-dev"
#        variables:
#          LIBMONGOC_VERSION: "r1.25"
#      - id: "latest-dev"
#        display_name: "master"
#        variables:
#          LIBMONGOC_VERSION: "master"

buildvariants:
  - matrix_name: "test-php-versions"
    matrix_spec:
      os:
        - debian11
        - debian10
        - rhel90
        - rhel83-zseries
        - rhel82-arm64
        - rhel81-power8
        - rhel80
        - rhel76
        - ubuntu2204-arm64
        - ubuntu2204
        - ubuntu2004-arm64
        - ubuntu2004
      mongodb-edge-versions: latest-stable
      php-versions: "*"
    display_name: "${os}, ${mongodb-edge-versions}, ${php-versions}"
    exclude_spec:
      # Exclude "latest-stable" PHP version for Debian 11 (see: test-mongodb-versions matrix)
      - { "os": "debian11", "mongodb-edge-versions": "*", "php-versions": "8.2" }
      # Exclude PHP versions older than 8.1 on RHEL 9 and Ubuntu 22.04 (OpenSSL 3 is only supported on PHP 8.1+)
      - { "os": ["rhel90", "ubuntu2204-arm64", "ubuntu2204"], "mongodb-edge-versions": "*", "php-versions": ["7.4", "8.0"] }
    tasks:
      - name: "test-standalone-ssl"
      - name: "test-replicaset-auth"
      - name: "test-sharded"

  # Test all topologies and MongoDB versions with latest-stable PHP version on Debian
  - matrix_name: "test-mongodb-versions"
    matrix_spec: { "os": ["debian92", "debian11"], "mongodb-versions": "*", "php-edge-versions": "latest-stable" }
    display_name: "${os}, ${mongodb-versions}, ${php-edge-versions}"
    exclude_spec:
      # Debian 9.2 only supports up to MongoDB 5.0
      - { "os": "debian92", "mongodb-versions": ["6.0", "7.0", "rapid", "latest"], "php-edge-versions": "latest-stable" }
      - { "os": "debian11", "mongodb-versions": ["3.6", "4.0", "4.2", "4.4", "5.0"], "php-edge-versions": "latest-stable" }
    tasks:
      - name: "test-standalone"
      - name: "test-standalone-auth"
      - name: "test-standalone-ssl"
      - name: "test-replicaset"
      - name: "test-replicaset-auth"
      - name: "test-sharded"

  # Test alternative storage engines on MongoDB 4.0
  - matrix_name: "test-storage-engines"
    matrix_spec: { "os": "debian92", "mongodb-versions": "4.0", "php-edge-versions": "latest-stable", "storage-engine": ["inmemory", "mmapv1"] }
    display_name: "${storage-engine}: ${os}, ${mongodb-edge-versions}, ${php-edge-versions}"
    tasks:
      - name: "test-standalone"

  - matrix_name: "libmongoc-versions"
    matrix_spec: { "os": "debian11", "mongodb-edge-versions": "latest-stable", "php-edge-versions": "latest-stable", "libmongoc-version": "*" }
    display_name: "libmongoc ${libmongoc-version}: ${os}, ${mongodb-edge-versions}, ${php-edge-versions}"
    tasks:
      - name: "test-standalone-ssl"
      - name: "test-replicaset-auth"
      - name: "test-sharded"

  - matrix_name: "atlas-connectivity-tests"
    matrix_spec: { "os": "debian11", "php-edge-versions": "latest-stable" }
    display_name: "Atlas Connectivity"
    tasks:
      - name: "test-atlas"

  - matrix_name: "test-ocsp"
    matrix_spec: { "os": "debian10", "mongodb-versions": "*", "php-edge-versions": "latest-stable" }
    display_name: "OCSP tests - ${mongodb-versions}"
    exclude_spec:
      # OCSP is available from MongoDB 4.4+ (Debian 10 has MongoDB 4.4+)
      - { "os": "debian10", "mongodb-versions": ["3.6", "4.0", "4.2"], "php-edge-versions": "latest-stable" }
    tasks:
      - name: ".ocsp"

  - matrix_name: "test-requireApiVersion"
    matrix_spec: { "os": "debian11", "mongodb-versions": "*", "php-edge-versions": "latest-stable" }
    display_name: "Versioned API - ${mongodb-versions}"
    exclude_spec:
      # Stable API is available from MongoDB 5.0+
      - { "os": "debian11", "mongodb-versions": ["3.6", "4.0", "4.2", "4.4"], "php-edge-versions": "latest-stable" }
    tasks:
      - name: "test-requireApiVersion"

  - matrix_name: "test-loadBalanced"
    matrix_spec: { "os": "debian11", "mongodb-versions": "*", "php-edge-versions": "latest-stable" }
    display_name: "Load balanced - ${mongodb-versions}"
    exclude_spec:
      # Load balancer is available from MongoDB 5.0+
      - { "os": "debian11", "mongodb-versions": ["3.6", "4.0", "4.2", "4.4"], "php-edge-versions": "latest-stable" }
    tasks:
      - name: "test-loadBalanced"

  - matrix_name: "test-csfle-skip_crypt_shared"
    matrix_spec: { "os": "debian11", "mongodb-versions": "*", "php-edge-versions": "latest-stable" }
    display_name: "CSFLE skip_crypt_shared - ${mongodb-versions}"
    exclude_spec:
      # CSFLE crypt_shared is available from MongoDB 6.0+
      - { "os": "debian11", "mongodb-versions": ["3.6", "4.0", "4.2", "4.4", "5.0"], "php-edge-versions": "latest-stable" }
    tasks:
      - name: "test-skip_crypt_shared"
