tasks:
  - name: "test-loadBalanced"
    tags: ["loadbalanced"]
    commands:
      - func: "compile driver"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "sharded_cluster"
          LOAD_BALANCER: "true"
          SSL: "yes"
      - func: "start load balancer"
      - func: "run tests"
        vars:
          # Note: loadBalanced=true should already be appended to SINGLE_MONGOS_LB_URI
          MONGODB_URI: "${SINGLE_MONGOS_LB_URI}"
          SSL: "yes"
      # Note: "stop load balancer" will be called from "post"

  - name: "test-requireApiVersion"
    tags: ["versioned_api"]
    commands:
      - func: "compile driver"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          AUTH: "auth"
          REQUIRE_API_VERSION: "yes"
      - func: "run tests"
        vars:
          API_VERSION: "1"

  - name: "ocsp-test_1-rsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_1"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-mustStaple.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-test_1-ecdsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_1"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-mustStaple.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-test_1-rsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_1"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-mustStaple.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-test_1-ecdsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_1"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-mustStaple.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-test_2-rsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_2"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-mustStaple.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-test_2-ecdsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_2"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-mustStaple.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-test_2-rsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_2"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-mustStaple.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-test_2-ecdsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_2"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-mustStaple.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-test_3-rsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_3"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-test_3-ecdsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_3"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-test_3-rsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_3"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-test_3-ecdsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_3"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-test_4-rsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_4"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-test_4-ecdsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_4"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-test_4-rsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_4"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-test_4-ecdsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "TEST_4"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-soft_fail_test-rsa"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-soft_fail_test-ecdsa"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-success.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-malicious_server_test_1-rsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "MALICIOUS_SERVER_TEST_1"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-mustStaple-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-malicious_server_test_1-ecdsa-delegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "MALICIOUS_SERVER_TEST_1"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "on"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-mustStaple-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-malicious_server_test_1-rsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "MALICIOUS_SERVER_TEST_1"
          CERT_TYPE: "rsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-mustStaple-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-malicious_server_test_1-ecdsa-nodelegate"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "run OCSP responder"
        vars:
          TEST_COLUMN: "MALICIOUS_SERVER_TEST_1"
          CERT_TYPE: "ecdsa"
          USE_DELEGATE: "off"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-mustStaple-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
  - name: "ocsp-malicious_server_test_2-rsa"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "rsa-basic-tls-ocsp-mustStaple-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/rsa/ca.pem"
  - name: "ocsp-malicious_server_test_2-ecdsa"
    tags: ["ocsp"]
    commands:
      - func: "compile driver"
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "ecdsa-basic-tls-ocsp-mustStaple-disableStapling.json"
      - func: "run tests"
        vars:
          TESTS: "tests/ocsp-failure.phpt"
          APPEND_URI: "/?tls=true&tlsCAFile=${DRIVERS_TOOLS}/.evergreen/ocsp/ecdsa/ca.pem"
