# When a task that used to pass starts to fail, go through all versions that may have been skipped to detect when the
# task started failing.
stepback: true

# Mark a failure as a system/bootstrap failure (purple box) rather than a task failure by default.
# Actual testing tasks are marked with `type: test`
command_type: system

# Protect ourselves against rogue test case that runs forever
# Good rule of thumb: the average length a task takes, times 5, which roughly accounts for variable system performance
# for various build variants
exec_timeout_secs: 1800

include:
  - filename: .evergreen/config/functions.yml

  - filename: .evergreen/config/build-tasks.yml
  - filename: .evergreen/config/build-task-groups.yml
  - filename: .evergreen/config/build-variants.yml

  - filename: .evergreen/config/test-tasks.yml
  - filename: .evergreen/config/test-task-groups.yml
  - filename: .evergreen/config/test-variants.yml
