# When a task that used to pass starts to fail, go through all versions that may have been skipped to detect when the
# task started failing.
stepback: true

# Mark a failure as a system/bootstrap failure (purple box) rather than a task failure by default.
# Actual testing tasks are marked with `type: test`
command_type: system

# Protect ourselves against rogue test case that runs forever
# Good rule of thumb: the average length a task takes, times 5, which roughly accounts for variable system performance
# for various build variants
exec_timeout_secs: 1800

# These pre and post rules apply to all tasks not part of a task group, which should only ever be tests against local
# MongoDB instances. All other tasks that require special preparation should be run from within a task group
pre: &test_setup
  - func: "fetch source"
  - func: "prepare resources"
  - func: "windows fix"
  - func: "fix absolute paths"
  - func: "init test-results"
  - func: "make files executable"
  - func: "install dependencies"
  - func: "fetch build"
post: &test_teardown
  - func: "upload mo artifacts"
  - func: "upload test results"
  - func: "stop mongo-orchestration"
  - func: "stop load balancer"
  - func: "upload working dir"
  - func: "cleanup"

include:
  - filename: .evergreen/config/functions.yml

  - filename: .evergreen/config/build-tasks.yml
  - filename: .evergreen/config/build-task-groups.yml
  - filename: .evergreen/config/build-variants.yml

  # Local deployments - these files are generated automatically
  - filename: .evergreen/config/test/local-latest.yml
  - filename: .evergreen/config/test/local-rapid.yml
  - filename: .evergreen/config/test/local-7.0.yml
  - filename: .evergreen/config/test/local-6.0.yml
  - filename: .evergreen/config/test/local-5.0.yml
  - filename: .evergreen/config/test/local-4.4.yml
  - filename: .evergreen/config/test/local-4.2.yml
  - filename: .evergreen/config/test/local-4.0.yml
  - filename: .evergreen/config/test/local-3.6.yml
  - filename: .evergreen/config/test/skip-crypt-shared.yml
  - filename: .evergreen/config/test/require-api-version.yml
  - filename: .evergreen/config/test/load-balanced.yml
  - filename: .evergreen/config/test/ocsp-latest.yml
  - filename: .evergreen/config/test/ocsp-rapid.yml
  - filename: .evergreen/config/test/ocsp-7.0.yml
  - filename: .evergreen/config/test/ocsp-6.0.yml
  - filename: .evergreen/config/test/ocsp-5.0.yml
  - filename: .evergreen/config/test/ocsp-4.4.yml

  - filename: .evergreen/config/test-tasks.yml
  - filename: .evergreen/config/test-variants.yml
