name: "Check generated arginfo files"

on:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "feature/*"

env:
  PHP_VERSION: "8.2"

jobs:
  check-arginfo:
    name: "Check generated arginfo files"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          submodules: true

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ env.PHP_VERSION }}"

      - name: "Run phpize"
        run: phpize

      - name: "Rebuild arginfo files from stubs"
        run: "php ./build/gen_stub.php --force-regeneration"

      - name: "Check arginfo file diff"
        run: git add . -N && git diff --exit-code
