name: "Build package files"

on:
  push:
    # TODO: Remove this branch once we're done testing
    branches:
      - "release-tooling"
    tags:
      - "*"

jobs:
  build-pecl:
    name: "Create release package"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2
          submodules: true

      - name: "Build Driver"
        uses: ./.github/workflows/linux/build
        with:
          version: "8.3"

      # TODO: create changelog from tag description
      - name: "Add dummy changelog"
        if: ${{ github.ref_type != 'tag' }}
        run: "echo 'Development Build' > changelog"

      - name: "Build package.xml"
        run: "make package.xml"

      - name: "Build release archive"
        run: "make package"

      # PECL always uses the version for the package name.
      # Read it from the version file and store in env to use when uploading artifacts
      - name: "Read current package version"
        run: echo "PACKAGE_VERSION=$(./bin/update-release-version.php version)" >> "$GITHUB_ENV"

      # Currently fails with: Cannot install, php_dir for channel "pecl.php.net" is not writeable by the current user
      # - name: "Install release archive to verify correctness"
      #  run: pecl install mongodb-${{ env.PACKAGE_VERSION }}.tgz

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: mongodb-${{ env.PACKAGE_VERSION }}.tgz
          path: mongodb-${{ env.PACKAGE_VERSION }}.tgz
          retention-days: 3

      - name: "Upload release artifact"
        if: ${{ github.ref_type == 'tag' }}
        run: gh release upload ${{ github.ref_name }} mongodb-${{ env.PACKAGE_VERSION }}.tgz
        # Until we've changed the process to always have a release draft, ignore errors during upload
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
