name: "Coding Standards"

on:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "feature/*"

env:
  PHP_VERSION: "8.1"

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          submodules: true

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ env.PHP_VERSION }}"

      - name: "Configure driver"
        run: .github/workflows/configure.sh

      - name: "Run clang-format"
        run: "make format-check"
