name: "Tests"

on:
  pull_request:
    branches:
      - "v*.*"
      - "master"
  push:
    branches:
      - "v*.*"
      - "master"

jobs:
  tests:
    name: "Tests"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: true
      matrix:
        os:
          - "ubuntu-20.04"
        php-version:
          - "7.4"
          - "8.0"
          # Re-enable after PHPC-1849 is resolved
          # - "8.1"
        mongodb-version:
          - "4.4"
        topology:
          - "server"
        include:
          - os: "ubuntu-20.04"
            php-version: "8.0"
            mongodb-version: "4.4"
            topology: "replica_set"
          - os: "ubuntu-20.04"
            php-version: "8.0"
            mongodb-version: "4.4"
            topology: "sharded_cluster"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2
          submodules: true

      - id: setup-mongodb
        uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          version: ${{ matrix.mongodb-version }}
          topology: ${{ matrix.topology }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: ":mongodb"
          tools: "phpize"

      - name: "Configure driver"
        run: .github/workflows/configure.sh

      - name: "Build driver"
        run: "make all"

      - name: "Run Tests"
        run: TEST_PHP_ARGS="-q -x --show-diff -g FAIL,XFAIL,BORK,WARN,LEAK,SKIP" make test
        env:
          MONGODB_URI: ${{ steps.setup-mongodb.outputs.cluster-uri }}
