name: "Windows Tests"
run-name: "Windows Tests (PHP ${{ inputs.php }} ${{ inputs.arch }} ${{ inputs.ts }})"

on:
  workflow_call:
    inputs:
      php:
        description: "The PHP version to build for"
        type: string
        required: true
      arch:
        description: "The architecture to build for (x64 or x86)"
        type: string
        required: true
      ts:
        description: "Thread safety (ts or nts)"
        type: string
        required: true
      upload_release_asset:
        description: "Whether to upload a release asset"
        type: boolean
        default: false

jobs:
  build:
    name: "Build Driver"
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Build Driver"
        id: build-driver
        uses: ./.github/actions/windows/build
        with:
          version: ${{ inputs.php }}
          arch: ${{ inputs.arch }}
          ts: ${{ inputs.ts }}

      - name: Cache build artifacts for subsequent builds
        id: cache-build-artifacts
        uses: actions/cache/save@v4
        with:
          key: ${{ github.sha }}-${{ inputs.php }}-${{ inputs.ts }}-${{ inputs.arch }}
          path: |
            ${{ steps.build-driver.outputs.build-dir }}\php_mongodb.dll
            ${{ steps.build-driver.outputs.build-dir }}\php_mongodb.pdb

  test:
    name: "Run Tests"
    runs-on: windows-2022
    needs: build
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - id: setup-mongodb
        uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          version: "7.0"
          topology: "server"

      - name: Prepare build environment
        id: prepare-build
        uses: ./.github/actions/windows/prepare-build
        with:
          version: ${{ inputs.php }}
          arch: ${{ inputs.arch }}
          ts: ${{ inputs.ts }}

      - name: Restore cached build artifacts
        id: cache-build-artifacts
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          key: ${{ github.sha }}-${{ inputs.php }}-${{ inputs.ts }}-${{ inputs.arch }}
          path: |
            ${{ steps.prepare-build.outputs.build-dir }}\php_mongodb.dll
            ${{ steps.prepare-build.outputs.build-dir }}\php_mongodb.pdb

      - name: Run Tests
        run: nmake /nologo test
        env:
          NO_INTERACTION: 1
          REPORT_EXIT_STATUS: 1
          TESTS: --show-diff
          MONGODB_URI: ${{ steps.setup-mongodb.outputs.cluster-uri }}
          CRYPT_SHARED_LIB_PATH: ${{ steps.setup-mongodb.outputs.crypt-shared-lib-path }}
